services:
  jekyll:
    image: gh-pages-env
    container_name: jekyll-container
    restart: always
    volumes:
      - .:/srv/jekyll # 当前目录挂载到容器
      # - /srv/jekyll/vendor/bundle # 缓存 Gem 依赖
    ports:
      - "4000:4000" # 映射 Jekyll 默认端口
      - "45729:35729" # 映射 Jekyll 默认端口
    command: >
      sh -c "bundle install && bundle exec jekyll serve --host 0.0.0.0 -P 4000 -I -w -l"
